#!/usr/bin/env bash

echo -e "Running kali in docker ..."
xhost +local:
mkdir -p data
docker run --rm -it -e DISPLAY=:0 --net="host" -v /tmp/.X11-unix:/tmp/.X11-unix -v ~/Worspace/docker/kali-rolling/data:/kali nflatrea/kali-linux-large "$@"
xhost -local:
