name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Core Docker image
      run: docker build . --file Dockerfile --build-arg VERSION=core --tag kali-docker-core:$(date +%s)
